/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Lorena
 */
import Produtos.*;
import BD_Verdurao.*;
import Vendas.VendasDAO;
import Vendas.VendasService;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaCaixa extends javax.swing.JFrame {
    DefaultTableModel listaCompras;
    private DefaultListModel<String> sugestaoNome;
    BancoDeDados bd;
    ProdutoDAO pd;
    ProdutoService ps;
    BancodeDados_vendas bdv;
    VendasService vs;
    VendasDAO vd;
    /**
     * Creates new form Caixa
     */
    public TelaCaixa() {
        //setContentPane(new FundoCaixa());

        initComponents();
        list_buscarProduto.setVisible(false);
        completaJList();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Verdurão UFCat - Caixa");
        bd = new BancoDeDados();
        bd.conectar();
        pd = new ProdutoDAO(bd);
        ps = new ProdutoService(pd);
        bdv = new BancodeDados_vendas();
        vd = new VendasDAO(bdv);
        vs = new VendasService(ps,vd);
        
        listaCompras = (DefaultTableModel) tabela_compras.getModel();
        listaCompras.setRowCount(0);
        
        sugestaoNome = new DefaultListModel<>();
        list_buscarProduto.setModel(sugestaoNome);
        
    }
    
    public void TabelaComprasBD(int id, String nome,float preco, String tipo, float quantidade){
         try{
            listaCompras.addRow(new Object[]{id,nome,tipo,preco,quantidade});
          }
        catch(Exception erro){
            System.out.println(erro);
        }
    }
    
    private void completaJList() {
        // Model da lista
        sugestaoNome = new DefaultListModel<>();
        list_buscarProduto.setModel(sugestaoNome);

        // Listener do campo de texto
        campo_nomeProduto.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                campo_nomeProdutoActionPerformed(null);
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                campo_nomeProdutoActionPerformed(null);
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                campo_nomeProdutoActionPerformed(null);
            }
        });

        // Listener da lista
        list_buscarProduto.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selecionado = list_buscarProduto.getSelectedValue();
                if (selecionado != null) {
                    campo_nomeProduto.setText(selecionado);

                    // Preenche tipo
                    List<Produtos> todosProdutos = ps.dao.buscarTodos();
                    for (Produtos p : todosProdutos) {
                        if (p.getNome().equalsIgnoreCase(selecionado)) {
                            ComboBox_tipo.setSelectedItem(p.getTipo());
                            break;
                        }
                    }

                    sugestaoNome.clear();
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_compras = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        label_tipo = new javax.swing.JLabel();
        label_produto = new javax.swing.JLabel();
        label_quantidade = new javax.swing.JLabel();
        btn_adicionarLista = new javax.swing.JButton();
        btn_removerLista = new javax.swing.JButton();
        label_total = new javax.swing.JLabel();
        campo_nomeProduto = new javax.swing.JTextField();
        list_buscarProduto = new javax.swing.JList<>();
        campo_quantidade = new javax.swing.JTextField();
        ComboBox_tipo = new javax.swing.JComboBox<>();
        btn_voltar = new javax.swing.JButton();
        vender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(410, 560));

        tabela_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome do Produto", "Tipo", "Preço por kg", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_comprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_compras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(410, 560));

        label_tipo.setText("Tipo:");

        label_produto.setText("Produto:");

        label_quantidade.setText("Quantidade (kg):");

        btn_adicionarLista.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btn_adicionarLista.setText("Adicionar à Lista");
        btn_adicionarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarListaActionPerformed(evt);
            }
        });

        btn_removerLista.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btn_removerLista.setText("Remover da Lista");
        btn_removerLista.setToolTipText("");
        btn_removerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerListaActionPerformed(evt);
            }
        });

        label_total.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        label_total.setText(" TOTAL: R$//setText depois para alterar ");
        label_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        campo_nomeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        campo_nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeProdutoActionPerformed(evt);
            }
        });

        list_buscarProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        list_buscarProduto.setPreferredSize(new java.awt.Dimension(64, 22));
        list_buscarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_buscarProdutoMouseClicked(evt);
            }
        });

        ComboBox_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdura", "Fruta", "Legume" }));
        ComboBox_tipo.setMaximumSize(new java.awt.Dimension(77, 32767));
        ComboBox_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_adicionarLista)
                        .addGap(49, 49, 49)
                        .addComponent(btn_removerLista))
                    .addComponent(label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_produto)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(label_tipo)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campo_nomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addComponent(list_buscarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(40, 40, 40))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_quantidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_tipo)
                    .addComponent(ComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_produto)
                    .addComponent(campo_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_buscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quantidade)
                    .addComponent(campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionarLista)
                    .addComponent(btn_removerLista))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        list_buscarProduto.getAccessibleContext().setAccessibleParent(campo_nomeProduto);

        btn_voltar.setBackground(new java.awt.Color(153, 255, 153));
        btn_voltar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(0, 0, 0));
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        vender.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        vender.setText("Finalizar Venda");
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vender, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addGap(426, 426, 426))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vender)
                .addGap(204, 204, 204)
                .addComponent(btn_voltar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_tipoActionPerformed
        
    }//GEN-LAST:event_ComboBox_tipoActionPerformed

    private void btn_adicionarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarListaActionPerformed
        // TODO add your handling code here:                                           
        // TODO add your handling code here:
        String nome = campo_nomeProduto.getText();
        if(pd.produtoExiste(nome)){
            float qtd = Float.parseFloat(campo_quantidade.getText());
            float qtdTotal = pd.obterQuantidadePorNome(nome);

            if(qtd<=qtdTotal){
                String tipo = (String) ComboBox_tipo.getSelectedItem();
                int id = pd.obterIdPorNome(nome);
                float preco = pd.obterPrecoPorNome(nome);
                TabelaComprasBD(id,nome.toUpperCase(), preco, tipo, qtd);
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Quantidade inexistente!\nQuantidade de '' "+nome+"'' em estoque: "+qtdTotal);
                campo_quantidade.setText("");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(rootPane, "Esse produto não está cadastrado");
            campo_nomeProduto.setText("");
        }                                                

    }//GEN-LAST:event_btn_adicionarListaActionPerformed

    private void btn_removerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerListaActionPerformed
        // TODO add your handling code here:
        int click = tabela_compras.getSelectedRow();
        if(click!=-1){
           ((DefaultTableModel) tabela_compras.getModel()).removeRow(click);
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleção não correspondente");
        }
    }//GEN-LAST:event_btn_removerListaActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void campo_nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeProdutoActionPerformed
        // TODO add your handling code here:
        String letras = campo_nomeProduto.getText().trim().toUpperCase();
        sugestaoNome.clear();

        if (!letras.isEmpty()) {
            list_buscarProduto.setVisible(true);
            List<Produtos> todosProdutos = ps.dao.buscarTodos(); // pega produtos do banco
            for (Produtos p : todosProdutos) {
                if (p.getNome().toUpperCase().startsWith(letras)) {
                    sugestaoNome.addElement(p.getNome());
                }
            }
        }
    }//GEN-LAST:event_campo_nomeProdutoActionPerformed

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tabela_compras.getModel();
    int rowCount = model.getRowCount();

    if (rowCount == 0) {
        JOptionPane.showMessageDialog(this, "Nenhum produto na lista para vender.");
        return;
    }

    float totalVenda = 0;

    for (int i = 0; i < rowCount; i++) {
        String nomeProduto = (String) model.getValueAt(i, 1); // Coluna 1 = Nome
        float quantidade = Float.parseFloat(model.getValueAt(i, 4).toString()); // Coluna 4 = Quantidade

        // Atualiza o estoque
        boolean vendido = ps.vender(nomeProduto, quantidade);

        if (vendido) {
            // Registra no banco
            vs.registrarVenda(nomeProduto, quantidade);

            // Soma ao total
            float preco = Float.parseFloat(model.getValueAt(i, 3).toString()); // Coluna 3 = Preço por kg
            totalVenda += preco * quantidade;
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao vender produto: " + nomeProduto);
        }
    }

    // Atualiza label do total
    label_total.setText("TOTAL: R$ " + String.format("%.2f", totalVenda));

    JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!");
    model.setRowCount(0); // Limpa a tabela depois da venda
    }//GEN-LAST:event_venderActionPerformed

    private void tabela_comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_comprasMouseClicked
        // TODO add your handling code here:
        btn_removerLista.setEnabled(true);
    }//GEN-LAST:event_tabela_comprasMouseClicked

    private void list_buscarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_buscarProdutoMouseClicked
        // TODO add your handling code here:
        list_buscarProduto.setVisible(false);
    }//GEN-LAST:event_list_buscarProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_tipo;
    private javax.swing.JButton btn_adicionarLista;
    private javax.swing.JButton btn_removerLista;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField campo_nomeProduto;
    private javax.swing.JTextField campo_quantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_produto;
    private javax.swing.JLabel label_quantidade;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JLabel label_total;
    private javax.swing.JList<String> list_buscarProduto;
    private javax.swing.JTable tabela_compras;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
