/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Matheus
 */
import Produtos.*;
import BD_Verdurao.*;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

public class TelaCadastro extends javax.swing.JFrame {
    String modoCadastro;
    
    BancoDeDados bd;
    ProdutoDAO pd;
    ProdutoService ps;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setLocationRelativeTo(null);
        bd = new BancoDeDados();
        bd.conectar();
        pd = new ProdutoDAO(bd);
        ps = new ProdutoService(pd);
        modoCadastro = "Navegar";
        manipularInterfaceCadastro();
    }
    
    public void manipularInterfaceCadastro(){
        switch(modoCadastro){
            case("Navegar"):
                Campo_nomeProduto.setEnabled(false);
                Campo_quantidade.setEnabled(false);
                ComboBox_tipo.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(true);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(false);
                btn_cancelar.setEnabled(false);
                break;
                
            case("Novo"):
                Campo_nomeProduto.setEnabled(true);
                Campo_quantidade.setEnabled(true);
                ComboBox_tipo.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
                
            case("Editar"):
                Campo_nomeProduto.setEnabled(true);
                Campo_quantidade.setEnabled(true);
                ComboBox_tipo.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_cadastroProdutos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        panel_cadastrarProduto = new javax.swing.JPanel();
        label_nomeProduto = new javax.swing.JLabel();
        Campo_nomeProduto = new javax.swing.JTextField();
        label_tipo = new javax.swing.JLabel();
        ComboBox_tipo = new javax.swing.JComboBox<>();
        label_quantidade = new javax.swing.JLabel();
        Campo_quantidade = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_cadastroProdutos.setText("Cadastro de Produtos");

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome do Produto", "Tipo", "Quantidade", "Preço por unidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_produtos);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        panel_cadastrarProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produtos"));

        label_nomeProduto.setText("Nome do Produto:");

        label_tipo.setText("Tipo:");

        ComboBox_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdura", "Fruta", "Legume" }));
        ComboBox_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_tipoActionPerformed(evt);
            }
        });

        label_quantidade.setText("Quantidade:");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cadastrarProdutoLayout = new javax.swing.GroupLayout(panel_cadastrarProduto);
        panel_cadastrarProduto.setLayout(panel_cadastrarProdutoLayout);
        panel_cadastrarProdutoLayout.setHorizontalGroup(
            panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                        .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_quantidade)
                                    .addComponent(label_nomeProduto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cadastrarProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label_tipo)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Campo_nomeProduto)
                            .addComponent(ComboBox_tipo, 0, 264, Short.MAX_VALUE)
                            .addComponent(Campo_quantidade)))
                    .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btn_salvar)
                        .addGap(78, 78, 78)
                        .addComponent(btn_cancelar)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_cadastrarProdutoLayout.setVerticalGroup(
            panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tipo))
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quantidade)
                    .addComponent(Campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addGap(17, 17, 17))
        );

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_cadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btn_novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_editar)
                                .addGap(57, 57, 57)
                                .addComponent(btn_excluir)
                                .addGap(46, 46, 46))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(label_cadastroProdutos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(btn_voltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_cadastroProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(panel_cadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_novo)
                            .addComponent(btn_editar)
                            .addComponent(btn_excluir))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(65, 65, 65)
                .addComponent(btn_voltar)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        Campo_quantidade.setText("");
        Campo_nomeProduto.setText("");
        modoCadastro = "Novo";
        manipularInterfaceCadastro();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirActionPerformed

    
    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {                                           
    try {
        int quantidade = Integer.parseInt(Campo_quantidade.getText());
        String tipo = (String) ComboBox_tipo.getSelectedItem();
        
        ps.CadastrarProduto(Campo_nomeProduto.getText(), 1, tipo, quantidade);
        
        JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!");
        modoCadastro = "Navegar";
        manipularInterfaceCadastro();
    } 
    catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantidade inválida. Digite apenas números.");
    } 
    catch (NullPointerException e) {
        JOptionPane.showMessageDialog(this, "Erro: campos não preenchidos corretamente.");
    }
}
    /*
    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
          int quantidade = Integer.parseInt(Campo_quantidade.getText());
          String tipo = (String) ComboBox_tipo.getSelectedItem();
          
          ps.CadastrarProduto(Campo_nomeProduto.getText(), 1, tipo, quantidade);
          
          
    }//GEN-LAST:event_btn_salvarActionPerformed
*/
    
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(rootPane, "Descartar alterações?","Aviso",JOptionPane.YES_NO_OPTION, 3);
        if(op==0){
            Campo_quantidade.setText("");
        Campo_nomeProduto.setText("");
        modoCadastro = "Navegar";
        manipularInterfaceCadastro();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void ComboBox_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_nomeProduto;
    private javax.swing.JTextField Campo_quantidade;
    private javax.swing.JComboBox<String> ComboBox_tipo;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cadastroProdutos;
    private javax.swing.JLabel label_nomeProduto;
    private javax.swing.JLabel label_quantidade;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JPanel panel_cadastrarProduto;
    private javax.swing.JTable tabela_produtos;
    // End of variables declaration//GEN-END:variables
}
