/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Matheus
 */
import Produtos.*;
import BD_Verdurao.*;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaCadastro extends javax.swing.JFrame {
    String modoCadastro;
    
    BancoDeDados bd;
    ProdutoDAO pd;
    ProdutoService ps;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setLocationRelativeTo(null);
        bd = new BancoDeDados();
        bd.conectar();
        pd = new ProdutoDAO(bd);
        ps = new ProdutoService(pd);
        modoCadastro = "Navegar";
        manipularInterfaceCadastro();
        TabelaCadastroBD();
    }
    
    public void TabelaCadastroBD(){
        DefaultTableModel tabela = new DefaultTableModel(new Object[] {"ID", "Nome do Produto","Tipo","Preço por kg","Quantidade" },0);
        List<Produtos> todosProdutos = ps.dao.buscarTodos();
        
        
        try{
          for(Produtos p : todosProdutos ){
            tabela.addRow(new Object[]{p.getId(),p.getNome(),p.getTipo(),p.getPreco(),p.getQuantidade()});
          }  
        }
        catch(Exception erro){
            System.out.println(erro);
        }
        tabela_produtos.setModel(tabela);
    }
    public void manipularInterfaceCadastro(){
        switch(modoCadastro){
            case("Navegar"):
                Campo_nomeProduto.setEnabled(false);
                Campo_quantidade.setEnabled(false);
                Campo_preco.setEnabled(false);
                ComboBox_tipo.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(true);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(false);
                btn_cancelar.setEnabled(false);
                break;
                
            case("Novo"):
                Campo_nomeProduto.setEnabled(true);
                Campo_quantidade.setEnabled(true);
                ComboBox_tipo.setEnabled(true);
                Campo_preco.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
                
            case("Editar"):
                Campo_nomeProduto.setEnabled(true);
                Campo_quantidade.setEnabled(true);
                ComboBox_tipo.setEnabled(true);
                Campo_preco.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_novo.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_salvar.setEnabled(true);
                btn_cancelar.setEnabled(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_cadastroProdutos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_novo = new javax.swing.JButton();
        panel_cadastrarProduto = new javax.swing.JPanel();
        label_nomeProduto = new javax.swing.JLabel();
        Campo_nomeProduto = new javax.swing.JTextField();
        label_tipo = new javax.swing.JLabel();
        ComboBox_tipo = new javax.swing.JComboBox<>();
        label_quantidade = new javax.swing.JLabel();
        Campo_quantidade = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Campo_preco = new javax.swing.JTextField();
        btn_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(label_cadastroProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 14, -1, -1));

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome do Produto", "Tipo", "Preço por kg", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_produtos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 434, 410));

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        panel_cadastrarProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produtos"));
        panel_cadastrarProduto.setForeground(new java.awt.Color(0, 0, 0));

        label_nomeProduto.setText("Nome do Produto:");

        label_tipo.setText("Tipo:");

        ComboBox_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verdura", "Fruta", "Legume" }));
        ComboBox_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_tipoActionPerformed(evt);
            }
        });

        label_quantidade.setText("Quantidade (em kg) :");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Preço por kg:");

        Campo_preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_precoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cadastrarProdutoLayout = new javax.swing.GroupLayout(panel_cadastrarProduto);
        panel_cadastrarProduto.setLayout(panel_cadastrarProdutoLayout);
        panel_cadastrarProdutoLayout.setHorizontalGroup(
            panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_quantidade)
                            .addComponent(label_nomeProduto)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cadastrarProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_tipo)))
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_nomeProduto)
                    .addComponent(ComboBox_tipo, 0, 264, Short.MAX_VALUE)
                    .addComponent(Campo_quantidade)
                    .addComponent(Campo_preco))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btn_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addGap(86, 86, 86))
        );
        panel_cadastrarProdutoLayout.setVerticalGroup(
            panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarProdutoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tipo))
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_quantidade)
                    .addComponent(Campo_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campo_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panel_cadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_cancelar))
                .addGap(17, 17, 17))
        );

        getContentPane().add(panel_cadastrarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_projetos/Produtos.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        Campo_quantidade.setText("");
        Campo_nomeProduto.setText("");
        Campo_preco.setText("");
        modoCadastro = "Novo";
        manipularInterfaceCadastro();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        modoCadastro = "Editar";
        manipularInterfaceCadastro();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
        int click = tabela_produtos.getSelectedRow();
        if(click!=-1){
            String id = tabela_produtos.getValueAt(click, 0).toString();
            String nome = (String) tabela_produtos.getValueAt(click, 1);
            
            int excluir = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir o produto \"" + nome + "\"?","Confirmar exclusão", JOptionPane.YES_NO_OPTION);
            if(excluir == 0){
                try {
                    ps.ExcluirProduto(Integer.parseInt(id)); // precisa ter esse método no ProdutoService/DAO
                    JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                    TabelaCadastroBD(); // recarrega tabela
                 } 
                catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                }
            }
            else{
                modoCadastro="Navegar";
                manipularInterfaceCadastro();
            }
            TabelaCadastroBD();
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        try{
            String nome = Campo_nomeProduto.getText();
            float quantidade = Float.parseFloat(Campo_quantidade.getText());
            if(quantidade <= 0){
                JOptionPane.showMessageDialog(rootPane, "A quantidade deve ser maior do que 0.","Quantidade inválida",2);
                Campo_quantidade.setText("");
                Campo_nomeProduto.setText("");
                Campo_preco.setText("");
                modoCadastro = "Navegar";
                manipularInterfaceCadastro();
                return;
            }
            String tipo = (String) ComboBox_tipo.getSelectedItem();
            float preco = Float.parseFloat(Campo_preco.getText());
            if(preco <= 0){
                JOptionPane.showMessageDialog(rootPane, "O preço deve ser maior do que 0.","Preço inválido",2);
                Campo_quantidade.setText("");
                Campo_nomeProduto.setText("");
                Campo_preco.setText("");
                modoCadastro = "Navegar";
                manipularInterfaceCadastro();
                return;
            }
            if(modoCadastro.equals("Novo")){
               ps.CadastrarProduto(nome, preco, tipo, quantidade);
               JOptionPane.showMessageDialog(rootPane, "Produto salvo com sucesso!", "Cadastro", 1);  
            }
            else if(modoCadastro.equals("Editar")){
                int id = ps.obterIdPorNome(nome);
                ps.EditarProduto(id,nome, preco, tipo, quantidade);
                JOptionPane.showMessageDialog(rootPane, "Produto editado com sucesso!", "Edição", 1);  
            } 
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Dados inválidos. Preencha corretamente os campos.","Dados inválidos",2);
        }
        catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro: campos não preenchidos corretamente.", "Campos vazios", 2);
         }
        
        TabelaCadastroBD();
        Campo_quantidade.setText("");
        Campo_nomeProduto.setText("");
        Campo_preco.setText("");
        modoCadastro = "Navegar";
        manipularInterfaceCadastro();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(rootPane, "Descartar alterações?","Aviso",JOptionPane.YES_NO_OPTION, 3);
        if(op==0){
            Campo_quantidade.setText("");
            Campo_nomeProduto.setText("");
            Campo_preco.setText("");
            modoCadastro = "Navegar";
            manipularInterfaceCadastro();
        }
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void ComboBox_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_tipoActionPerformed

    private void Campo_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_precoActionPerformed

    private void tabela_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_produtosMouseClicked
        // TODO add your handling code here:
        int click = tabela_produtos.getSelectedRow();
        if(click!=-1){
            String nome = (String) tabela_produtos.getValueAt(click, 1);
            String tipo = (String) tabela_produtos.getValueAt(click, 2);
            String preco = tabela_produtos.getValueAt(click, 3).toString();
            String quantidade = tabela_produtos.getValueAt(click, 4).toString();
            
            Campo_nomeProduto.setText(nome);
            Campo_preco.setText(preco);
            ComboBox_tipo.setSelectedItem(tipo);
            Campo_quantidade.setText(quantidade);
            
            btn_editar.setEnabled(true);
            btn_excluir.setEnabled(true);
        }
    }//GEN-LAST:event_tabela_produtosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_nomeProduto;
    private javax.swing.JTextField Campo_preco;
    private javax.swing.JTextField Campo_quantidade;
    private javax.swing.JComboBox<String> ComboBox_tipo;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_cadastroProdutos;
    private javax.swing.JLabel label_nomeProduto;
    private javax.swing.JLabel label_quantidade;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JPanel panel_cadastrarProduto;
    private javax.swing.JTable tabela_produtos;
    // End of variables declaration//GEN-END:variables
}
