/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import javax.swing.JOptionPane;
/**
 *
 * @author Lorena
 */
public class TelaLogin extends javax.swing.JFrame {
    private final String usuario = "Verdurao";
    private final String senha = "verdura2025";
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {

        initComponents();
        getRootPane().setDefaultButton(btn_entrar);
        setLocationRelativeTo(null);
        setTitle("Verdurão UFCat - Área de Login");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_usuario = new javax.swing.JLabel();
        campo_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        campo_senha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 0));
        setMaximumSize(new java.awt.Dimension(445, 334));
        setMinimumSize(new java.awt.Dimension(445, 334));
        setPreferredSize(new java.awt.Dimension(396, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_usuario.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_usuario.setForeground(new java.awt.Color(255, 255, 255));
        label_usuario.setText("Usuário: ");
        getContentPane().add(label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        campo_usuario.setBackground(new java.awt.Color(255, 255, 255));
        campo_usuario.setForeground(new java.awt.Color(0, 0, 0));
        campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 240, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bem Vindo(a)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 127, 35));

        btn_entrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_entrar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        campo_senha.setBackground(new java.awt.Color(255, 255, 255));
        campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 240, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Efetue seu login:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 350, 120));

        label_titulo.setBackground(new java.awt.Color(0, 51, 0));
        label_titulo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(0, 0, 0));
        label_titulo.setText("Área de Login - Verdurão UFCat");
        getContentPane().add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        if(usuario.equals(campo_usuario.getText()) && senha.equals(campo_senha.getText())){
            TelaPrincipal tp = new TelaPrincipal();
            tp.setVisible(true); 
            dispose();
        }
        //verificar campos vazios, e ENTER pra entrar
        else{
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválidos!\nTente novamente.", "Aviso", 0);
            campo_usuario.setText("");
            campo_senha.setText("");
        }
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campo_usuarioActionPerformed

    private void campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_senhaActionPerformed
        
    }//GEN-LAST:event_campo_senhaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JPasswordField campo_senha;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_usuario;
    // End of variables declaration//GEN-END:variables
}
